### ISSUE TITLE
How can I get whether a test suite passed or failed in TestListener?

### ISSUE THREAD

**Issue by gitzyong812** [katalon-studio-samples/katalon-web-automation#2]
TestListener is a new feature for katalon 5.2. 
I add a sampleAfterTestSuite hook, and there is a TestSuiteContext instance. 
How can I get whether a test suite passed or failed? 
Is there any document or source code for TestSuiteContext?
![image](https://user-images.githubusercontent.com/11305113/34403323-91442480-ebe2-11e7-9b24-cd4744a0d1a3.png)

**Comment by vinhpnguyen** [comment]
There is no status for a test suite, so you can't get whether it is passed or failed.

**Comment by gitzyong812** [comment]
@vinhpnguyen 
Thank you for reply. 
How about getting how many test cases failed?

Because I want to add a hook which can notify me by sms or phone call if there are failed cases, but the testSuiteContext provides so little information and I can't find detailed docs of it.

**Comment by vinhpnguyen** [comment]
Hi there,

Please find below sample code to resolve your current concern as a workaround solution:

```
import java.util.concurrent.atomic.AtomicInteger
import com.kms.katalon.core.annotation.AfterTestCase
import com.kms.katalon.core.annotation.AfterTestSuite
import com.kms.katalon.core.context.TestCaseContext
import com.kms.katalon.core.context.TestSuiteContext

class NewTestListener {
	AtomicInteger passedTC = new AtomicInteger(0)
	AtomicInteger failedTC = new AtomicInteger(0)

	/**
	 * Executes after every test case ends.
	 * @param testCaseContext related information of the executed test case.
	 */
	@AfterTestCase
	def sampleAfterTestCase(TestCaseContext testCaseContext) 
	{
		if (testCaseContext.getTestCaseStatus() == 'PASSED')
		{
			passedTC.andIncrement()
		}
		else if (testCaseContext.getTestCaseStatus() == 'FAILED')
		{
			failedTC.andIncrement()
		}
	}

	/**
	 * Executes after every test suite ends.
	 * @param testSuiteContext: related information of the executed test suite.
	 */
	@AfterTestSuite
	def sampleAfterTestSuite(TestSuiteContext testSuiteContext)
	{
		println "Number of passed TCs is: " + passedTC.get()
		println "Number of failed TCs is: " + failedTC.get()
	}
}
```
Regards to information about either TestSuiteContext or TestCaseContext, actually the sample methods generated from sample template are all of available functions within these contexts and they are quite easily understandable, so I think that's why there is no further documentation for the current Test Listeners

**Comment by gitzyong812** [comment]
@vinhpnguyen 
It can help to solve my problem. Thank you so much
