### ISSUE TITLE
Reports have no logs in Katalon 5.2 Log Viewer on Windows

### ISSUE THREAD

**Issue by gitzyong812** [katalon-studio-samples/katalon-web-automation#4]
Katalon is running on Windows 10, Katalon 5.2.

I run test suites by using the test suite collection 

As the snapshoot shows, reports have no logs in Katalon log viewer 
![image](https://user-images.githubusercontent.com/11305113/34564803-3124139c-f193-11e7-91f3-28341d275359.png)

**Comment by cansuarslancom** [comment]
is there still any problem?
