### ISSUE TITLE
How to solve "org.eclipse.core.internal.dtree.NoDataDeltaNode"?

### ISSUE THREAD

**Issue by gitzyong812** [katalon-studio-samples/katalon-web-automation#5]
![image](https://user-images.githubusercontent.com/11305113/34858295-850ef59c-f78a-11e7-8f80-7a7e7214c542.png)

Hi, I have the problem as image shows. I have no idea.

Katalon version: 5.2.0
OS: Windows

```
org.eclipse.core.internal.dtree.NoDataDeltaNode cannot be cast to org.eclipse.core.internal.dtree.DataTreeNode
```

**Comment by vinhpnguyen** [comment]
Hi Yong,

You should post your issue on Katalon Forum. This 'Issues' is used for issues within this provided project, not Katalon Studio. :)

**Comment by gitzyong812** [comment]
@vinhpnguyen ok, I can't upload image on Katalon Forum. I have the same problem there, and use the image url from here.
